url: "https://lyoxa.ch"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


# SEO
title: "Lyoxa - Consulting associatif"
description: "Lyoxa est une plateforme de conseils gratuits, de soutien et de collaboration entre les différents acteur·trice·s de la vie associative dans le Canton de Genève."
